### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by Ayfri** [maximousblk/ghlog#1]
Every time I try to use it I get an empty changelog with no commits and no contributors :/
`ghlog Advanced-Command-Handler/Advanced-Command-Handler`

**Comment by maximousblk** [comment]
😅 Sorry, that's on me for not documenting properly. This module only works correctly is your contributors follow conventional commit format.

**Comment by Ayfri** [comment]
Hm, if I use a custom template, can I get this to work?

**Comment by maximousblk** [comment]
It will work but you won't get the categorisation because there is no metadata to use.

**Comment by Ayfri** [comment]
Not a problem with my changelogs, thanks!
(And don't forget to document more precisely 😉)
