### ISSUE TITLE
Cannot read property 'login' of null

### ISSUE THREAD

**Issue by Ayfri** [maximousblk/ghlog#2]
Hi again, I'm getting this error in this repo `Ayfri/2d-minecraft`:
```ts
error: Uncaught (in promise) TypeError: Cannot read property 'login' of null
            author: commit.author.login,
                            ^
    at getCommitsBetween (utils.ts:104:29)
    at async getChanges (utils.ts:131:10)
    at async getChangeLog (main.ts:12:31)
    at async defaultChangelog (mod.ts:7:20)
    at async ghlog.ts:27:21
```
I know that I modified the template and a bit the code but I didn't change the `getCommitsBetween` function so it's not my fault.

**Comment by maximousblk** [comment]
the error is coming from the commit [ Ayfri/2d-minecraft@`46b5123`](https://github.com/Ayfri/2d-minecraft/commit/46b5123f2b97aa7e123c42fcaf8efa200bb09cca) which is seemingly committed using an email that is not registered (or removed?) on GitHub.

I'll see if I can work around this
