### ISSUE TITLE
Why is there no support for multiple templates?

### ISSUE THREAD

**Issue by Ayfri** [maximousblk/ghlog#4]
I think that you should make multiple differents templates, ones with categories, ones without, one without emojis, etc, and let us select it through the CLI (with a `--template` argument for example).
This would greatly improve this project!

**Comment by maximousblk** [comment]
I knew someone would ask 😃

I originally wanted this to be more of a DIY solution where you have the info and you can arrange it as you desire and do whatever with the output.

I would add multiple templates but there is so much info and so many ways to create changelogs and everyone wants it to be a certain way. so I only have one (opinionated) template by default and export all the info (sorted and unsorted) for people to create their own.

for example, in the default template, I put a link to the commit with the short hash. some like to have the link on the commit text, some like to put it on the end, some only like to put the hash but not a link, some people would prefer not to have it altogether. this would either require me to add every requested template, or create a templating language which is dynamic enough. I'd rather that language be javascript/typescript than creating my own.

**Comment by Ayfri** [comment]
Mh I see, but for example:
When I tried to modify this to only have only 1 "Changelog" category, I struggled a lot because code is very axed for multiple categories, maybe you should change this, like regrouping every part of the configuration in 1 ts file?

**Comment by maximousblk** [comment]
if you just want a list of commits, you can do something like:

```ts
// ghlog@0.2.x
const { _meta } = await getChangeLog("owner/repo");
const changelog = `CHANGELOG

${ _meta.commits.all.map(({ message }) => `- ${message}` ).join("\n") }
`

// write `changelog` to file
```

I'm trying to think of a good way for how to structure the output of `getChangeLog()` so that it's as flexible as possible.

**Comment by Ayfri** [comment]
Mh I see okay, I was just doing it badly!
