### ISSUE TITLE
Merge commits with same message.

### ISSUE THREAD

**Issue by Ayfri** [maximousblk/ghlog#5]
Hi, I think that commits with the same message should be merged like this :
```markdown
<!--- before : -->
- Message. (sha1)
- Message. (sha2)
- Message. (sha3)

<!--- after : -->
- Message. (sha1) (sha2) (sha3)
```

**Comment by maximousblk** [comment]
I think this should be done by the user.

This would also cause problems if someone wants them to be separate, because merging messages is easier than separating them back.

**Comment by maximousblk** [comment]
BTW I'm releasing `0.3.0` soon which would make this task much easier 😉

**Comment by Ayfri** [comment]
Oh nice !

**Comment by maximousblk** [comment]
@Ayfri [v0.3.0](https://github.com/maximousblk/ghlog/releases/tag/0.3.0) released! 🙂
